name: 'taxi_co2'
version: '1.0.0'
config-version: 2

profile: 'taxi_co2'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

models:
  nyc_taxi_emissions:
    staging:
      +materialized: table
